import { dayOfYear } from "./dates.js";

export const WORDS = [
  { word: "Ephemeral", meaning: "Lasting for a very short time." },
  { word: "Sonder", meaning: "The realization that each passerby has a life as vivid as your own." },
  { word: "Petrichor", meaning: "The pleasant smell after rain on dry earth." },
  { word: "Ineffable", meaning: "Too great to be expressed in words." },
  { word: "Serendipity", meaning: "Finding something good without looking for it." },
  { word: "Luminous", meaning: "Full of or shedding light; bright." },
  { word: "Resilience", meaning: "The capacity to recover quickly from difficulties." },
  { word: "Wanderlust", meaning: "A strong desire to travel and explore." },
  { word: "Halcyon", meaning: "Denoting a period of time that was idyllically happy." },
  { word: "Mellifluous", meaning: "A sound that is sweet and smooth, pleasing to hear." },
  { word: "Equanimity", meaning: "Mental calmness in a difficult situation." },
  { word: "Effervescent", meaning: "Vivacious and enthusiastic." },
  { word: "Nostalgia", meaning: "A sentimental longing for the past." },
  { word: "Ubiquitous", meaning: "Present or found everywhere." },
  { word: "Quintessential", meaning: "Representing the most perfect example of a quality." },
  { word: "Solitude", meaning: "The state of being alone, often by choice." },
  { word: "Cognizant", meaning: "Having knowledge or awareness of something." },
  { word: "Eloquent", meaning: "Fluent and persuasive in speaking or writing." },
  { word: "Fortitude", meaning: "Courage in facing pain or adversity." },
  { word: "Gratitude", meaning: "The quality of being thankful." },
  { word: "Intrepid", meaning: "Fearless and adventurous." },
  { word: "Jubilant", meaning: "Feeling or expressing great happiness." },
  { word: "Kinetic", meaning: "Relating to or resulting from motion." },
  { word: "Lucid", meaning: "Clear and easy to understand; clear-headed." },
  { word: "Magnanimous", meaning: "Generous or forgiving, especially toward a rival." },
  { word: "Nuance", meaning: "A subtle difference in meaning or expression." },
  { word: "Oblivious", meaning: "Not aware of what is happening around you." },
  { word: "Pragmatic", meaning: "Dealing with things sensibly and realistically." },
  { word: "Quaint", meaning: "Attractively unusual or old-fashioned." },
  { word: "Resolute", meaning: "Admirably purposeful and determined." },
  { word: "Serene", meaning: "Calm, peaceful, and untroubled." },
  { word: "Tenacious", meaning: "Holding firmly to a course of action." },
  { word: "Unwavering", meaning: "Steady and not changing." },
  { word: "Vivacious", meaning: "Attractively lively and animated." },
  { word: "Whimsical", meaning: "Playfully quaint or fanciful." },
  { word: "Zenith", meaning: "The highest point reached; the peak." },
  { word: "Amiable", meaning: "Having a friendly and pleasant manner." },
  { word: "Buoyant", meaning: "Cheerful and optimistic." },
  { word: "Candor", meaning: "The quality of being open and honest." },
  { word: "Diligent", meaning: "Showing care and effort in work or duties." },
];

export const FACTS = [
  "Honey never spoils if stored properly — archaeologists have found edible honey in ancient Egyptian tombs.",
  "Octopuses have three hearts and blue blood.",
  "A day on Venus is longer than a year on Venus.",
  "Bananas are botanically berries, but strawberries are not.",
  "The human body has enough iron to make a 3-inch nail.",
  "Sharks existed before trees.",
  "Your brain uses about 20% of your body's total energy.",
  "Sea otters hold hands while sleeping so they don't drift apart.",
  "A single cloud can weigh more than a million pounds.",
  "Wombat droppings are cube-shaped.",
  "The Eiffel Tower can grow taller in summer due to heat expansion.",
  "There are more possible chess games than atoms in the observable universe.",
  "Hot water can freeze faster than cold water under certain conditions.",
  "Cows have best friends and get stressed when separated.",
  "Your nose can detect over a trillion different scents.",
  "Butterflies taste with their feet.",
  "It rains diamonds on Jupiter and Saturn.",
  "The shortest war in history lasted 38 minutes.",
  "Some turtles can breathe through their butts.",
  "A group of flamingos is called a flamboyance.",
  "The heart of a shrimp is located in its head.",
  "Bamboo can grow up to 35 inches in a single day.",
  "There's a species of jellyfish that is biologically immortal.",
  "Your stomach gets an entirely new lining every few days so it doesn't digest itself.",
  "Polar bears have black skin under their white fur.",
  "The inventor of the frisbee was turned into a frisbee after he died.",
  "Elephants are one of the few animals that can recognize themselves in a mirror.",
  "A single strand of spaghetti is called a spaghetto.",
  "Scotland's national animal is the unicorn.",
  "It would take about 1,000 years to watch a light-year in a car driving at highway speed.",
  "A blue whale's heart is the size of a small car.",
  "Some cats are allergic to humans.",
  "Venus is the only planet that rotates clockwise.",
  "The dot over a lowercase 'i' or 'j' is called a tittle.",
  "Koalas have fingerprints so similar to humans they can confuse crime scenes.",
  "A day on the planet Mercury lasts longer than its year.",
  "Starfish don't have brains or blood.",
  "There are more stars in the universe than grains of sand on every beach on Earth.",
  "Crows can hold grudges against specific people for years.",
  "The Great Wall of China is not visible from space with the naked eye, despite the myth.",
];

export function contentOfTheDay(date = new Date()) {
  const idx = dayOfYear(date);
  return {
    word: WORDS[idx % WORDS.length],
    fact: FACTS[idx % FACTS.length],
  };
}
